name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
          
    - name: Set up environment variables
      run: |
        echo "Setting up environment variables"
        export $(grep -v '^#' .env | xargs)

    - name: Install dependencies and run tests
      run: |
        echo "Installing dependencies"
        pip install -r requirements.txt
        echo "Running tests"
        pytest

     

