name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
          
    - name: Set up environment variables
      run: |
        echo "Setting up environment variables"
        export $(grep -v '^#' .env | xargs)

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install -r requirements.txt

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@latest

    - name: Setup FirefoxDriver
      uses: browser-actions/setup-firefox@latest

    - name: Start Selenium Server HUB
      run: nohup java -jar selenium-server-4.17.0.jar hub & sleep 5
      shell: bash

    - name: Start Selenium Server nodes
      run: nohup java -jar selenium-server-4.17.0.jar node & sleep 5
      shell: bash
      
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#github_actions'
      if: always()

         
